PROGNAME=***SUBST_PROGNAME***
WERROR_FLAG=***SUBST_WERROR_FLAG***

OBJS = \
src/main.o \
src/args.o \
src/usage.o \
src/die.o \
src/sort.o \

LIBS = \
-lc -lm \

CC?=cc
LDFLAGS?=
CFLAGS=-std=c99 -Wall -Wextra -pedantic $(WERROR_FLAG) -Iinclude/

.PHONY: all clean distclean ee bee run test

all: $(PROGNAME)
clean:
	rm -vf $(PROGNAME) src/*.o tests/*.out
distclean: clean
	rm -vf Makefile

$(PROGNAME): $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o $(PROGNAME)
test: test.sh $(PROGNAME)
	test.sh "$(PROGNAME)"
# Debug targets
run: $(PROGNAME)
	./$(PROGNAME)
ee: clean run
bee: clean all
